### PR TITLE
Make augment.factanal() more robust. Fixes #604.

### LINKED ISSUE #604: augment method not working for `factanal` objects
``` r
set.seed(123)

# data
v1 <- c(1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,4,5,6)
v2 <- c(1,2,1,1,1,1,2,1,2,1,3,4,3,3,3,4,6,5)
v3 <- c(3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,5,4,6)
v4 <- c(3,3,4,3,3,1,1,2,1,1,1,1,2,1,1,5,6,4)
v5 <- c(1,1,1,1,1,3,3,3,3,3,1,1,1,1,1,6,4,5)
v6 <- c(1,1,1,2,1,3,3,3,4,3,1,1,1,2,1,6,5,4)
m1 <- cbind(v1,v2,v3,v4,v5,v6)

# tidy dataframe
broom::tidy(stats::factanal(m1, factors = 3))
#> # A tibble: 6 x 5
#>   variable uniqueness   fl1   fl2   fl3
#>   <chr>         <dbl> <dbl> <dbl> <dbl>
#> 1 v1           0.005  0.944 0.182 0.267
#> 2 v2           0.101  0.905 0.235 0.159
#> 3 v3           0.005  0.236 0.210 0.946
#> 4 v4           0.224  0.180 0.242 0.828
#> 5 v5           0.0843 0.242 0.881 0.286
#> 6 v6           0.005  0.193 0.959 0.196

# not supposed to work
broom::augment(stats::factanal(m1, factors = 3, scores = "none"))
#> Error: Cannot augment factanal objects fit with `scores = 'none'`.

# supposed to work
broom::augment(stats::factanal(m1, factors = 3, scores = "Bartlett"))
#> Error in data.frame(.rownames = rownames(scores), data.frame(scores)): arguments imply differing number of rows: 0, 18

# supposed to work
broom::augment(stats::factanal(m1, factors = 3, scores = "regression"))
#> Error in data.frame(.rownames = rownames(scores), data.frame(scores)): arguments imply differing number of rows: 0, 18

#> traceback()
7: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
6: data.frame(.rownames = rownames(scores), data.frame(scores))
5: eval(lhs, parent, parent)
4: eval(lhs, parent, parent)
3: data.frame(.rownames = rownames(scores), data.frame(scores)) %>% 
       as_tibble()
2: augment.factanal(factanal(m1, factors = 3, scores = "Bartlett"))
1: augment(factanal(m1, factors = 3, scores = "Bartlett"))
```

<sup>Created on 2019-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2018-11-30 r75724)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       America/New_York                                  
#>  date     2019-02-10                                        
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib source                           
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.1)                   
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.6.0)                   
#>  broom         0.5.1.9000 2019-01-20 [1] Github (tidymodels/broom@66411c4)
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.6.0)                   
#>  cli           1.0.1.9000 2019-01-20 [1] Github (r-lib/cli@94e2fc5)       
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                   
#>  desc          1.2.0      2019-01-21 [1] Github (r-lib/desc@42b9578)      
#>  devtools      2.0.1.9000 2019-01-29 [1] Github (r-lib/devtools@e4e57aa)  
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                   
#>  dplyr         0.8.0      2019-02-06 [1] Github (tidyverse/dplyr@cf0e282) 
#>  evaluate      0.12       2018-10-09 [1] CRAN (R 3.5.1)                   
#>  fansi         0.4.0      2018-11-05 [1] Github (brodieG/fansi@ab11e9c)   
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                   
#>  generics      0.0.2      2019-01-20 [1] Github (r-lib/generics@d59e6b4)  
#>  glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.1)                   
#>  highr         0.7        2018-06-09 [1] CRAN (R 3.5.1)                   
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                   
#>  knitr         1.21       2018-12-10 [1] CRAN (R 3.6.0)                   
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                   
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                   
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.6.0)                   
#>  pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                   
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                   
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                   
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                   
#>  processx      3.2.1      2018-12-05 [1] CRAN (R 3.6.0)                   
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                   
#>  purrr         0.3.0      2019-01-27 [1] CRAN (R 3.5.2)                   
#>  R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.1)                   
#>  Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.6.0)                   
#>  remotes       2.0.2      2018-10-30 [1] CRAN (R 3.6.0)                   
#>  rlang         0.3.1      2019-01-08 [1] CRAN (R 3.6.0)                   
#>  rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.6.0)                   
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                   
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                   
#>  stringi       1.2.4      2018-07-20 [1] CRAN (R 3.6.0)                   
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                   
#>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                   
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.6.0)                   
#>  tidyr         0.8.2      2018-10-28 [1] CRAN (R 3.6.0)                   
#>  tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                   
#>  usethis       1.4.0.9000 2019-02-11 [1] Github (r-lib/usethis@8e3c151)   
#>  utf8          1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                   
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                   
#>  xfun          0.4        2018-10-23 [1] CRAN (R 3.6.0)                   
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                   
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-devel/library
```

</details>

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
I have also updated the examples to reflect how specifying different scoring methods won't break any of the methods.

Here is a reprex:
``` r
set.seed(123)

# data
v1 <- c(1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,4,5,6)
v2 <- c(1,2,1,1,1,1,2,1,2,1,3,4,3,3,3,4,6,5)
v3 <- c(3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,5,4,6)
v4 <- c(3,3,4,3,3,1,1,2,1,1,1,1,2,1,1,5,6,4)
v5 <- c(1,1,1,1,1,3,3,3,3,3,1,1,1,1,1,6,4,5)
v6 <- c(1,1,1,2,1,3,3,3,4,3,1,1,1,2,1,6,5,4)
m1 <- cbind.data.frame(v1,v2,v3,v4,v5,v6)

# new data
m2 <-
  cbind.data.frame(
    x1 = rev(v1),
    x2 = rev(v2),
    x3 = rev(v3),
    x4 = rev(v4),
    x5 = rev(v5),
    x6 = rev(v6)
  )

# objects
x1 <- stats::factanal(m1, factors = 3, scores = "Bartlett")
x2 <- stats::factanal(m1, factors = 3, scores = "regression")

# tidying the object
broom::tidy(x1)
#> # A tibble: 6 x 5
#>   variable uniqueness   fl1   fl2   fl3
#>   <chr>         <dbl> <dbl> <dbl> <dbl>
#> 1 v1           0.005  0.944 0.182 0.267
#> 2 v2           0.101  0.905 0.235 0.159
#> 3 v3           0.005  0.236 0.210 0.946
#> 4 v4           0.224  0.180 0.242 0.828
#> 5 v5           0.0843 0.242 0.881 0.286
#> 6 v6           0.005  0.193 0.959 0.196
broom::tidy(x2)
#> # A tibble: 6 x 5
#>   variable uniqueness   fl1   fl2   fl3
#>   <chr>         <dbl> <dbl> <dbl> <dbl>
#> 1 v1           0.005  0.944 0.182 0.267
#> 2 v2           0.101  0.905 0.235 0.159
#> 3 v3           0.005  0.236 0.210 0.946
#> 4 v4           0.224  0.180 0.242 0.828
#> 5 v5           0.0843 0.242 0.881 0.286
#> 6 v6           0.005  0.193 0.959 0.196

# augmented dataframe
broom::augment(x1)
#> # A tibble: 18 x 4
#>    .rownames   .fs1   .fs2   .fs3
#>    <chr>      <dbl>  <dbl>  <dbl>
#>  1 1         -0.904 -0.931  0.948
#>  2 2         -0.869 -0.933  0.935
#>  3 3         -0.908 -0.932  0.962
#>  4 4         -1.00  -0.253  0.818
#>  5 5         -0.904 -0.931  0.948
#>  6 6         -0.745  0.727 -0.788
#>  7 7         -0.710  0.725 -0.801
#>  8 8         -0.750  0.726 -0.774
#>  9 9         -0.808  1.40  -0.930
#> 10 10        -0.745  0.727 -0.788
#> 11 11         0.927 -0.931 -0.837
#> 12 12         0.963 -0.933 -0.849
#> 13 13         0.923 -0.932 -0.823
#> 14 14         0.829 -0.253 -0.967
#> 15 15         0.927 -0.931 -0.837
#> 16 16         0.422  2.05   1.29 
#> 17 17         1.47   1.29   0.545
#> 18 18         1.88   0.309  1.95
broom::augment(x2)
#> # A tibble: 18 x 4
#>    .rownames   .fs1   .fs2   .fs3
#>    <chr>      <dbl>  <dbl>  <dbl>
#>  1 1         -0.897 -0.925  0.936
#>  2 2         -0.861 -0.927  0.924
#>  3 3         -0.901 -0.926  0.950
#>  4 4         -0.993 -0.251  0.809
#>  5 5         -0.897 -0.925  0.936
#>  6 6         -0.741  0.720 -0.784
#>  7 7         -0.706  0.718 -0.796
#>  8 8         -0.745  0.719 -0.770
#>  9 9         -0.803  1.39  -0.923
#> 10 10        -0.741  0.720 -0.784
#> 11 11         0.917 -0.925 -0.830
#> 12 12         0.952 -0.927 -0.842
#> 13 13         0.913 -0.926 -0.816
#> 14 14         0.820 -0.252 -0.958
#> 15 15         0.917 -0.925 -0.830
#> 16 16         0.426  2.04   1.28 
#> 17 17         1.46   1.29   0.548
#> 18 18         1.88   0.314  1.95

# augmented dataframe (with new data)
broom::augment(x1, data = m2)
#> # A tibble: 18 x 10
#>    .rownames    x1    x2    x3    x4    x5    x6   .fs1   .fs2   .fs3
#>    <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl>
#>  1 1             6     5     6     4     5     4 -0.904 -0.931  0.948
#>  2 2             5     6     4     6     4     5 -0.869 -0.933  0.935
#>  3 3             4     4     5     5     6     6 -0.908 -0.932  0.962
#>  4 4             3     3     1     1     1     1 -1.00  -0.253  0.818
#>  5 5             3     3     1     1     1     2 -0.904 -0.931  0.948
#>  6 6             3     3     1     2     1     1 -0.745  0.727 -0.788
#>  7 7             3     4     1     1     1     1 -0.710  0.725 -0.801
#>  8 8             3     3     1     1     1     1 -0.750  0.726 -0.774
#>  9 9             1     1     1     1     3     3 -0.808  1.40  -0.930
#> 10 10            1     2     1     1     3     4 -0.745  0.727 -0.788
#> 11 11            1     1     1     2     3     3  0.927 -0.931 -0.837
#> 12 12            1     2     1     1     3     3  0.963 -0.933 -0.849
#> 13 13            1     1     1     1     3     3  0.923 -0.932 -0.823
#> 14 14            1     1     3     3     1     1  0.829 -0.253 -0.967
#> 15 15            1     1     3     3     1     2  0.927 -0.931 -0.837
#> 16 16            1     1     3     4     1     1  0.422  2.05   1.29 
#> 17 17            1     2     3     3     1     1  1.47   1.29   0.545
#> 18 18            1     1     3     3     1     1  1.88   0.309  1.95
broom::augment(x2, data = m2)
#> # A tibble: 18 x 10
#>    .rownames    x1    x2    x3    x4    x5    x6   .fs1   .fs2   .fs3
#>    <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl>
#>  1 1             6     5     6     4     5     4 -0.897 -0.925  0.936
#>  2 2             5     6     4     6     4     5 -0.861 -0.927  0.924
#>  3 3             4     4     5     5     6     6 -0.901 -0.926  0.950
#>  4 4             3     3     1     1     1     1 -0.993 -0.251  0.809
#>  5 5             3     3     1     1     1     2 -0.897 -0.925  0.936
#>  6 6             3     3     1     2     1     1 -0.741  0.720 -0.784
#>  7 7             3     4     1     1     1     1 -0.706  0.718 -0.796
#>  8 8             3     3     1     1     1     1 -0.745  0.719 -0.770
#>  9 9             1     1     1     1     3     3 -0.803  1.39  -0.923
#> 10 10            1     2     1     1     3     4 -0.741  0.720 -0.784
#> 11 11            1     1     1     2     3     3  0.917 -0.925 -0.830
#> 12 12            1     2     1     1     3     3  0.952 -0.927 -0.842
#> 13 13            1     1     1     1     3     3  0.913 -0.926 -0.816
#> 14 14            1     1     3     3     1     1  0.820 -0.252 -0.958
#> 15 15            1     1     3     3     1     2  0.917 -0.925 -0.830
#> 16 16            1     1     3     4     1     1  0.426  2.04   1.28 
#> 17 17            1     2     3     3     1     1  1.46   1.29   0.548
#> 18 18            1     1     3     3     1     1  1.88   0.314  1.95
```

<sup>Created on 2019-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@alexpghayes Done!

File: R/stats-factanal-tidiers.R [hunk 1]
```diff
@@ -75,25 +106,35 @@ augment.factanal <- function(x, data, ...) {
...
-  data$.rownames <- rownames(data)
   tidy_df <- tidy_df %>% 
     dplyr::right_join(data, by = ".rownames")
 
   tidy_df %>% 
     dplyr::select(
-      .rownames, everything(),
-      -matches("\\.fs[0-9]*"), matches("\\.fs[0-9]*")
+      .rownames, dplyr::everything(),
+      -dplyr::matches("\\.fs[0-9]*"), dplyr::matches("\\.fs[0-9]*")
```
Comment (alexpghayes) [inline R/stats-factanal-tidiers.R]: Perhaps comment on what the regex does to make it easier to maintain this down the line?

File: tests/testthat/test-stats-factanal.R [hunk 2]
```diff
@@ -18,48 +18,105 @@ test_that("factanal tidier arguments", {
...
-  
+
   expect_equal(td$variable, colnames(mtcars))
   expect_equal(ncol(td2), 2 + n_factors2)
 })
 
 test_that("glance.factanal works", {
   gl <- glance(fit)
   gl2 <- glance(fit2)
-
```
Comment (alexpghayes) [inline tests/testthat/test-stats-factanal.R]: Where are all these whitespace changes coming from?

Comment (IndrajeetPatil) [reply tests/testthat/test-stats-factanal.R]: From running Styler

File: R/stats-factanal-tidiers.R [hunk 3]
```diff
@@ -75,25 +106,35 @@ augment.factanal <- function(x, data, ...) {
   }
 
   # Place relevant values into a tidy data frame
-  tidy_df <- data.frame(.rownames = rownames(scores), data.frame(scores)) %>%
-    as_tibble()
+  if (has_rownames(scores)) {
+    tidy_df <- data.frame(.rownames = rownames(scores), data.frame(scores)) %>%
```
[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply R/stats-factanal-tidiers.R]: I looked into this and I would prefer to not use it right now since I am actually not sure how that function is working. I will raise a separate issue maybe about its behavior.

**Comment by IndrajeetPatil** [comment]
@alexpghayes Done!

File: tests/testthat/test-stats-factanal.R [hunk 4]
```diff
@@ -18,48 +18,108 @@ test_that("factanal tidier arguments", {
...
+  fit1 <- stats::factanal(m1, factors = 3, scores = "Bartlett")
+  fit2 <- stats::factanal(m1, factors = 3, scores = "regression")
+
+  # augmented dataframe
+  df1 <- broom::augment(fit1)
+  df2 <- broom::augment(fit2)
+
+  # augmented dataframe (with new data)
+  df3 <- broom::augment(fit1, data = m2)
+  df4 <- broom::augment(fit2, data = m2)
```
Comment (alexpghayes) [inline tests/testthat/test-stats-factanal.R]: Is this supposed to test when `m2` is a matrix? But here `m2` is a data frame?

File: tests/testthat/test-stats-factanal.R [hunk 5]
```diff
@@ -18,48 +18,108 @@ test_that("factanal tidier arguments", {
...
+
+  # checking dataframe dimensions
+  testthat::expect_is(df1, "tbl_df")
```
Comment (alexpghayes) [inline tests/testthat/test-stats-factanal.R]: Let's use modeltests `check_tidy_output()` and `check_dims()` to make this a bit more concise.

File: tests/testthat/test-stats-factanal.R [hunk 6]
```diff
@@ -18,48 +18,108 @@ test_that("factanal tidier arguments", {
...
+  set.seed(123)
+  
+  # data
+  v1 <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 4, 5, 6)
+  v2 <- c(1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 3, 4, 3, 3, 3, 4, 6, 5)
+  v3 <- c(3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 4, 6)
+  v4 <- c(3, 3, 4, 3, 3, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 5, 6, 4)
+  v5 <- c(1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 6, 4, 5)
+  v6 <- c(1, 1, 1, 2, 1, 3, 3, 3, 4, 3, 1, 1, 1, 2, 1, 6, 5, 4)
+  fit1 <- cbind.data.frame(v1, v2, v3, v4, v5, v6)
```
[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply tests/testthat/test-stats-factanal.R]: Actually, with these new changes, the code in the example won't work here because this is no longer a dataframe but a matrix.

**Comment by IndrajeetPatil** [comment]
@alexpghayes All comments addressed.

File: tests/testthat/test-stats-factanal.R (hunk 4 above)
Comment (IndrajeetPatil) [reply tests/testthat/test-stats-factanal.R]: Good catch! This has been resolved.
